export const DATA_SOURCE = 'DATA_SOURCE';
export const ANSWER_REPOSITORY = 'ANSWER_REPOSITORY';
export const QUESTION_REPOSITORY = 'QUESTION_REPOSITORY';
export const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
